### ISSUE TITLE
QPoint(): too many arguments error at program runtime

### ISSUE THREAD

**Issue by ibrahimeth** [blauret/pyG5#12]
first of all thank you for PyG5
I want to use it in a project I made, but I could not run PyG5.
so ı clone this repo but ı am taking thats error
``
pyG5\pyG5View.py", line 753, in
paintEvent
     self.qp.drawText(QPoint(30 + 3, height + 2), str(int(pitch))) #, str(int(pitch))
TypeError: arguments did not match any overloaded call:
   QPoint(): too many arguments
   QPoint(int, int): argument 2 has unexpected type 'float'
   QPoint(QPoint): argument 1 has unexpected type 'int'
``
I get an error and I cant found how to fix this error 
My pyqt5 versions are as follows
``PyQt5              5.15.7 ``
``PyQt5-Qt5          5.15.2``
``PyQt5-sip          12.11.0``
``pyqt5ac            1.2.1``
Thank you

**Comment by blauret** [comment]
it's linked to the pyqt version. The secondary_screen branch has the fixes but probably things you don't want. I need to separate those. Either you merge manually or you wait I get back to it.

**Comment by ibrahimeth** [comment]
Thank you! I am going to try to fix. So, in my opinion its depend on PyQt5 versions . I'll change QPoint Arguments in your pyG5View.py file.

**Comment by blauret** [comment]
I moved to Qt6. I don't see issues either on macOS for arm or Raspberrypi. I'll close for now. Let me know if you still see issues.
