### ISSUE TITLE
Thanks for pyG5 codebase it looks great... I have questions if u dont mind

### ISSUE THREAD

**Issue by jerryfat** [blauret/pyG5#13]
Hi Ben:
THANKS ! I have learned allot from you and your apps
I like your pyG5 apps very much
I have made my own listener in network manager to recv a udp pickled dictionary sent from my JerryGCS app over UDP on github: https://github.com/jerryfat/JerryGCS is not up to date yet I am on ver 139 
Thanks for your clver and neat code, still trying to understand it all,  very nice job
I dont understand how you update or what you update when you get new data from xplane
I am using PX4 JMavSim, QGCS over mavlink and my app sends attitude pickle dict based on dronekit and PyQt5
I see you emit a signal but I dont understand how it works yet.
If you can explain or give me hint
I am classic UNIX C/C++ trained and love Python and PyQt5, it took long time and effort to build my app.
I can open a hundred windows to monitor mavlink data messages from PX JMAVSiim

as a test I added to pyG5Network.py:

class pyG5_PX4_UDPListener(QObject):
    """pyG5_PX4_UDPListener Object.

    Args:
        parent: Parent Widget

    Returns:
        self
    """
    xpInstance = pyqtSignal(QHostAddress, int)
    drefUpdate = pyqtSignal(dict) # will only bind if in a class and is instantiated

    def __init__(self, parent=None):
        print("inside class pyG5_PX4_UDPListener(QObject): __init__")
        """Object constructor.
        
        Args:
            parent: Parent Widget

        Returns:
            self
        """
        QObject.__init__(self, parent)

        self.logger = logging.getLogger(self.__class__.__name__)

        self.XPAddr = QHostAddress("127.0.0.1") #"239.255.1.1")
        self.XPPort = 65432 #49707

        # create the socket
        self.udpSock = QUdpSocket(self)

        self.udpSock.stateChanged.connect(self.stateChangedSlot)
        self.udpSock.readyRead.connect(self.udpData)
        self.udpSock.connected.connect(self.connectedSlot)
        self.udpSock.bind(QHostAddress.Null, self.XPPort, QUdpSocket.ShareAddress) #self.udpSock.bind(QHostAddress.AnyIPv4, self.XPPort, QUdpSocket.ShareAddress)
        #if not self.udpSock.joinMulticastGroup(self.XPAddr):
        #    logging.error("Failed to join multicast group")

    @pyqtSlot(QAbstractSocket.SocketState)
    def stateChangedSlot(self, state):
        """stateChangedSlot."""
        self.logger.debug("Sock new state: {}".format(state))

    @pyqtSlot()
    def connectedSlot(self):
        """connectedSlot."""
        self.logger.debug("udp connected: {}".format(self.udpSock.state()))

    @pyqtSlot()
    def udpData(self):
        """udpData."""
        print("inside class pyG5NetWorkManager(QObject): udpData())")
        while self.udpSock.hasPendingDatagrams():
            data = self.udpSock.receiveDatagram()
            print("inside class pyG5NetWorkManager(QObject): len(data), data= ", len(data.data()), " , ", data.data() )
            if (len(data.data()) < 5):
                return
            data_dict = pickle.loads(data.data())
            # if data_dict has entries then emit
            print("Received data_dict= ", data_dict )   
            for k, v in data_dict.items():
                print(k, v)
            print("Received len(data_dict), len(data_dict.keys(), data_dict.keys()=", len(data_dict), len(data_dict.keys()), data_dict.keys() )
            print("data_dict=", data_dict["'roll'"])
            print("data_dict=", data_dict["'pitch'"])
            print("data_dict=", data_dict["'yaw'"])
            retvalues = {}
            datarefs = [
                # ( dataref, frequency, unit, description, num decimals to display in formatted output )
                (
                    "sim/flightmodel/position/mag_psi",
                    30,
                    "°",
                    "Magnetic heading of the aircraft",
                    0,
                    "_magHeading",
                ),
                (
                    "sim/flightmodel/position/phi",
                    30,
                    "°",
                    "Roll of the aircraft",
                    0,
                    "_rollAngle",
                ),
                (
                    "sim/flightmodel/position/theta",
                    30,
                    "°",
                    "Pitch of the aircraft",
                    0,
                    "_pitchAngle",
                ), 
                ]
            numvalues = 1 #test with rollAngle #int(len(values) / lenvalue)
            idx = 0
            value = 0
            for i in range(0, numvalues):
                #singledata = data[(5 + lenvalue * i) : (5 + lenvalue * (i + 1))]
                #(idx, value) = struct.unpack("<if", singledata)
                idx = 1
                value = '10.0' #data_dict["'roll'"]
                retvalues[idx] = (
                    value,
                    datarefs[idx][1],
                    datarefs[idx][0],
                    datarefs[idx][5],
                    )
            self.drefUpdate.emit(retvalues)
            break
            #if "BECN" in str(datagram.data())[2:6]:
            #    self.xpInstance.emit(
            #        datagram.senderAddress(),
            #        int.from_bytes(bytes(datagram.data())[19:21], byteorder="little"),
            #    )
            #    self.udpSock.leaveMulticastGroup(self.XPAddr)
            #self.udpSock.close()

**Comment by jerryfat** [comment]
Hi Ben:
I figured out my problem , I was doing 'emit' in wrong function, got your app to change roll angle, THANKS for a great app and code, learned allot

**Comment by blauret** [comment]
Cool, glad you found out this issue. That's a cool project you are running, keep me posted. Happy to see this thing coming alive.

**Comment by jerryfat** [comment]
Hi:Thank you again.I am an RC flyer of fixed wing airplanes, and a programmer.My eyes dont allow me to fly real planes, Otherwise I would be flying pigs over Ethiopia
I love flying too.
One weird question is how the package import PyG5. works in the code, I had to put local filename there
So,
I turned off the pyG5 tcp listener for now and made dataHandler in Network Manager do the parsing and receiving of the pickled dictionary message, simpler that way
I will update github JerryGCS project later today hopefully and will send u email of my code changes for u to see.I need to create a better readme.md
I apologize if I am crude programmer, I am amazed at your finesse
It has been allot of learning, you are very talented programmer

Your app looks beautiful too, you have artistic skills as well
How did u learn the tcp stuff it's brilliant how you do it ?
I created a mavlink monitor and then the ability to send data to pyG5I used PyQt5 so I can manage hundreds of windows if needed. I am in awe of pyQt5I will get some screenshots too for docs 
Thank you again,
Finest Regards,-Jerry Fat
 
 
 
-----Original Message-----

**Comment by jerryfat** [comment]
Hi, here is some hacked code I wrote that uses dronekit to start an ardupilot copter sitl in python and connect to a mapbox CherryPy html server for map in a browserits a combination of dronekit drone_delivery and a cherrypy demo using mapbox with token
I am running on Ubuntu 20 and Python 3.8There is a problem in Python 3.10 and 3.11 with collections abc package , I have an easy fix if needed
To install : download the 'mapbox20230209.py' and the zipped 'html.zip' folder and unzip
$ python3 mapbox20230209.py
and open map in browser :  http://127.0.0.1:8080/command

 -Jerry
P.S. I am adding this http CherryPy map to my JerryGCS app today
 Thanks again
---------------------------------------------'mapbox20230209.py'------------------------------------------------------------

#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
© Copyright 2015-2016, 3D Robotics.
drone_delivery.py:

A CherryPy based web application that displays a mapbox map to let you view the current vehicle position and send the vehicle commands to fly to a particular latitude and longitude.

Full documentation is provided at http://python.dronekit.io/examples/drone_delivery.html
#I have found the map ID at here https://www.mapbox.com/studio/tilesets/. It can be
#mapbox.satellite
#mapbox.terrain-rgb



"""

from __future__ import print_function
import os
import simplejson
import time

from dronekit import connect, VehicleMode, LocationGlobal, LocationGlobalRelative
import cherrypy
from jinja2 import Environment, FileSystemLoader

# Set up option parsing to get connection string
import argparse
parser = argparse.ArgumentParser(description='Creates a CherryPy based web application that displays a mapbox map to let you view the current vehicle position and send the vehicle commands to fly to a particular latitude and longitude. Will start and connect to SITL if no connection string specified.')
parser.add_argument('--connect',
                    help="vehicle connection target string. If not specified, SITL is automatically started and used.")
args = parser.parse_args()

connection_string = args.connect

# Start SITL if no connection , eg string empty
if not connection_string:
    import dronekit_sitl
    start_lat =  41.833474 #40.17904123640337 #, -74.6825621480185# 41.833474
    start_lon = -74.6825621480185 # -87.626819
    sitl = dronekit_sitl.start_default(start_lat, start_lon)   #sitl = dronekit_sitl.start_default()
    connection_string = sitl.connection_string()
    print("sitl.connection_string: ", connection_string)
local_path = os.path.dirname(os.path.abspath(__file__))
print("local path: %s" % local_path)


cherrypy_conf = {
    '/': {
        'tools.sessions.on': True,
        'tools.staticdir.root': local_path
    },
    '/static': {
        'tools.staticdir.on': True,
        'tools.staticdir.dir': './html/assets'
    }
}


class Drone(object):
    def __init__(self, server_enabled=True):
        self.gps_lock = False
        self.altitude = 30.0

        # Connect to the Vehicle
        self._log('Connected to vehicle.')
        self.vehicle = vehicle
        self.commands = self.vehicle.commands
        self.current_coords = []
        self.webserver_enabled = server_enabled
        self._log("DroneDelivery Start")

        # Register observers
        self.vehicle.add_attribute_listener('location', self.location_callback)

    def launch(self):
        self._log("Waiting for location...")
        while self.vehicle.location.global_frame.lat == 0:
            time.sleep(0.1)
        self.home_coords = [self.vehicle.location.global_frame.lat,
                            self.vehicle.location.global_frame.lon]
        
        self._log("self.vehicle.location.global_frame.lat:")
        self._log(self.vehicle.location.global_frame.lat)      
        self._log("self.vehicle.location.global_frame.lon:") 
        self._log(self.vehicle.location.global_frame.lon)    

        self._log("Waiting for ability to arm...")
        while not self.vehicle.is_armable:
            time.sleep(.1)

        self._log('Running initial boot sequence')
        self.change_mode('GUIDED')
        self.arm()
        self.takeoff()

        if self.webserver_enabled is True:
            self._run_server()

    def takeoff(self):
        self._log("Taking off")
        self.vehicle.simple_takeoff(30.0)

    def arm(self, value=True):
        if value:
            self._log('Waiting for arming...')
            self.vehicle.armed = True
            while not self.vehicle.armed:
                time.sleep(.1)
        else:
            self._log("Disarming!")
            self.vehicle.armed = False

    def _run_server(self):
        # Start web server if enabled
        cherrypy.tree.mount(DroneDelivery(self), '/', config=cherrypy_conf)

        cherrypy.config.update({'server.socket_port': 8080,
                                'server.socket_host': '0.0.0.0',
                                'log.screen': None})

        print('''Server is bound on all addresses, port 8080
You may connect to it using your web broser using a URL looking like this:
http://localhost:8080/
''')
        cherrypy.engine.start()

    def change_mode(self, mode):
        self._log("Changing to mode: {0}".format(mode))

        self.vehicle.mode = VehicleMode(mode)
        #while self.vehicle.mode.name != mode:
        self._log('  ... polled mode: {0}'.format(mode))
        #    time.sleep(1)

    def goto(self, location, relative=None):
        self._log("Goto: {0}, {1}".format(location, self.altitude))

        if relative:
            self.vehicle.simple_goto(
                LocationGlobalRelative(
                    float(location[0]), float(location[1]),
                    float(self.altitude)
                )
            )
        else:
            self.vehicle.simple_goto(
                LocationGlobal(
                    float(location[0]), float(location[1]),
                    float(self.altitude)
                )
            )
        self.vehicle.flush()

    def get_location(self):
        return [self.current_location.lat, self.current_location.lon]

    def location_callback(self, vehicle, name, location):
        if location.global_relative_frame.alt is not None:
            self.altitude = location.global_relative_frame.alt

        self.current_location = location.global_relative_frame

    def _log(self, message):
        print("[DEBUG]: {0}".format(message))


class Templates:
    def __init__(self, home_coords):
        self.home_coords = home_coords
        self.options = self.get_options()
        self.environment = Environment(loader=FileSystemLoader(local_path + '/html'))

    def get_options(self):
        return {'width': 670,
                'height': 470,
                'zoom': 13,
                'format': 'png',
                'access_token': 'pk.eyJ1IjoiamVycnlmYXQiLCJhIjoiY2tjczFwZnp0MDJuaDJ6cWpkZHF5YjM1cCJ9.8pwSnCZUuvsm8Tzm_LYt4g',
                'mapid': 'mapbox.satellite',
                'home_coords': self.home_coords,
                'menu': [{'name': 'Home', 'location': '/'},
                         {'name': 'Track', 'location': '/track'},
                         {'name': 'Command', 'location': '/command'}],
                'current_url': '/',
                'json': ''
                }
                # 'access_token': 'pk.eyJ1Ijoia2V2aW4zZHIiLCJhIjoiY2lrOGoxN2s2MDJzYnR6a3drbTYwdGxmMiJ9.bv5u7QgmcJd6dZfLDGoykw','mapid':           #'kevin3dr.n56ffjoo',
                #works for jerry
                # 'access_token': 'pk.eyJ1IjoiamVycnlmYXQiLCJhIjoiY2tjczFwZnp0MDJuaDJ6cWpkZHF5YjM1cCJ9.8pwSnCZUuvsm8Tzm_LYt4g',
                # 'mapid': 'mapbox.satellite',
                #mapbox.satellite
                #mapbox.terrain-rgb
                
    def index(self):
        self.options = self.get_options()
        self.options['current_url'] = '/'
        return self.get_template('index')

    def track(self, current_coords):
        self.options = self.get_options()
        self.options['current_url'] = '/track'
        self.options['current_coords'] = current_coords
        self.options['json'] = simplejson.dumps(self.options)
        return self.get_template('track')

    def command(self, current_coords):
        self.options = self.get_options()
        self.options['current_url'] = '/command'
        self.options['current_coords'] = current_coords
        return self.get_template('command')

    def get_template(self, file_name):
        template = self.environment.get_template(file_name + '.html')
        return template.render(options=self.options)


class DroneDelivery(object):
    def __init__(self, drone):
        self.drone = drone
        self.templates = Templates(self.drone.home_coords)

    @cherrypy.expose
    def index(self):
        return self.templates.index()

    @cherrypy.expose
    def command(self):
        return self.templates.command(self.drone.get_location())

    @cherrypy.expose
    @cherrypy.tools.json_out()
    def vehicle(self):
        return dict(position=self.drone.get_location())

    @cherrypy.expose
    def track(self, lat=None, lon=None):
        # Process POST request from Command
        # Sending MAVLink packet with goto instructions
        #self._log("TRACK() Goto: {0}, {1}".format(location, self.altitude))
        if(lat is not None and lon is not None):
            self.drone.goto([lat, lon], True)

        return self.templates.track(self.drone.get_location())


# Connect to the Vehicle
print('Connecting to vehicle on: %s' % connection_string)
vehicle = connect(connection_string, wait_ready=True)

print('Launching Drone...')
Drone().launch()

print('Waiting for cherrypy engine...')
cherrypy.engine.block()

if not args.connect:
    # Shut down simulator if it was started.
    sitl.stop()

# END# END# END# END# END# END


#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
© Copyright 2015-2016, 3D Robotics.
drone_delivery.py:

A CherryPy based web application that displays a mapbox map to let you view the current vehicle position and send the vehicle commands to fly to a particular latitude and longitude.

Full documentation is provided at http://python.dronekit.io/examples/drone_delivery.html
#I have found the map ID at here https://www.mapbox.com/studio/tilesets/. It can be
#mapbox.satellite
#mapbox.terrain-rgb



"""

from __future__ import print_function
import os
import simplejson
import time

from dronekit import connect, VehicleMode, LocationGlobal, LocationGlobalRelative
import cherrypy
from jinja2 import Environment, FileSystemLoader

# Set up option parsing to get connection string
import argparse
parser = argparse.ArgumentParser(description='Creates a CherryPy based web application that displays a mapbox map to let you view the current vehicle position and send the vehicle commands to fly to a particular latitude and longitude. Will start and connect to SITL if no connection string specified.')
parser.add_argument('--connect',
                    help="vehicle connection target string. If not specified, SITL is automatically started and used.")
args = parser.parse_args()

connection_string = args.connect

# Start SITL if no connection , eg string empty
if not connection_string:
    import dronekit_sitl
    start_lat =  41.833474 #40.17904123640337 #, -74.6825621480185# 41.833474
    start_lon = -74.6825621480185 # -87.626819
    sitl = dronekit_sitl.start_default(start_lat, start_lon)   #sitl = dronekit_sitl.start_default()
    connection_string = sitl.connection_string()
    print("sitl.connection_string: ", connection_string)
local_path = os.path.dirname(os.path.abspath(__file__))
print("local path: %s" % local_path)


cherrypy_conf = {
    '/': {
        'tools.sessions.on': True,
        'tools.staticdir.root': local_path
    },
    '/static': {
        'tools.staticdir.on': True,
        'tools.staticdir.dir': './html/assets'
    }
}


class Drone(object):
    def __init__(self, server_enabled=True):
        self.gps_lock = False
        self.altitude = 30.0

        # Connect to the Vehicle
        self._log('Connected to vehicle.')
        self.vehicle = vehicle
        self.commands = self.vehicle.commands
        self.current_coords = []
        self.webserver_enabled = server_enabled
        self._log("DroneDelivery Start")

        # Register observers
        self.vehicle.add_attribute_listener('location', self.location_callback)

    def launch(self):
        self._log("Waiting for location...")
        while self.vehicle.location.global_frame.lat == 0:
            time.sleep(0.1)
        self.home_coords = [self.vehicle.location.global_frame.lat,
                            self.vehicle.location.global_frame.lon]
        
        self._log("self.vehicle.location.global_frame.lat:")
        self._log(self.vehicle.location.global_frame.lat)      
        self._log("self.vehicle.location.global_frame.lon:") 
        self._log(self.vehicle.location.global_frame.lon)    

        self._log("Waiting for ability to arm...")
        while not self.vehicle.is_armable:
            time.sleep(.1)

        self._log('Running initial boot sequence')
        self.change_mode('GUIDED')
        self.arm()
        self.takeoff()

        if self.webserver_enabled is True:
            self._run_server()

    def takeoff(self):
        self._log("Taking off")
        self.vehicle.simple_takeoff(30.0)

    def arm(self, value=True):
        if value:
            self._log('Waiting for arming...')
            self.vehicle.armed = True
            while not self.vehicle.armed:
                time.sleep(.1)
        else:
            self._log("Disarming!")
            self.vehicle.armed = False

    def _run_server(self):
        # Start web server if enabled
        cherrypy.tree.mount(DroneDelivery(self), '/', config=cherrypy_conf)

        cherrypy.config.update({'server.socket_port': 8080,
                                'server.socket_host': '0.0.0.0',
                                'log.screen': None})

        print('''Server is bound on all addresses, port 8080
You may connect to it using your web broser using a URL looking like this:
http://localhost:8080/
''')
        cherrypy.engine.start()

    def change_mode(self, mode):
        self._log("Changing to mode: {0}".format(mode))

        self.vehicle.mode = VehicleMode(mode)
        #while self.vehicle.mode.name != mode:
        self._log('  ... polled mode: {0}'.format(mode))
        #    time.sleep(1)

    def goto(self, location, relative=None):
        self._log("Goto: {0}, {1}".format(location, self.altitude))

        if relative:
            self.vehicle.simple_goto(
                LocationGlobalRelative(
                    float(location[0]), float(location[1]),
                    float(self.altitude)
                )
            )
        else:
            self.vehicle.simple_goto(
                LocationGlobal(
                    float(location[0]), float(location[1]),
                    float(self.altitude)
                )
            )
        self.vehicle.flush()

    def get_location(self):
        return [self.current_location.lat, self.current_location.lon]

    def location_callback(self, vehicle, name, location):
        if location.global_relative_frame.alt is not None:
            self.altitude = location.global_relative_frame.alt

        self.current_location = location.global_relative_frame

    def _log(self, message):
        print("[DEBUG]: {0}".format(message))


class Templates:
    def __init__(self, home_coords):
        self.home_coords = home_coords
        self.options = self.get_options()
        self.environment = Environment(loader=FileSystemLoader(local_path + '/html'))

    def get_options(self):
        return {'width': 670,
                'height': 470,
                'zoom': 13,
                'format': 'png',
                'access_token': 'pk.eyJ1IjoiamVycnlmYXQiLCJhIjoiY2tjczFwZnp0MDJuaDJ6cWpkZHF5YjM1cCJ9.8pwSnCZUuvsm8Tzm_LYt4g',
                'mapid': 'mapbox.satellite',
                'home_coords': self.home_coords,
                'menu': [{'name': 'Home', 'location': '/'},
                         {'name': 'Track', 'location': '/track'},
                         {'name': 'Command', 'location': '/command'}],
                'current_url': '/',
                'json': ''
                }
                # 'access_token': 'pk.eyJ1Ijoia2V2aW4zZHIiLCJhIjoiY2lrOGoxN2s2MDJzYnR6a3drbTYwdGxmMiJ9.bv5u7QgmcJd6dZfLDGoykw','mapid':           #'kevin3dr.n56ffjoo',
                #works for jerry
                # 'access_token': 'pk.eyJ1IjoiamVycnlmYXQiLCJhIjoiY2tjczFwZnp0MDJuaDJ6cWpkZHF5YjM1cCJ9.8pwSnCZUuvsm8Tzm_LYt4g',
                # 'mapid': 'mapbox.satellite',
                #mapbox.satellite
                #mapbox.terrain-rgb
                
    def index(self):
        self.options = self.get_options()
        self.options['current_url'] = '/'
        return self.get_template('index')

    def track(self, current_coords):
        self.options = self.get_options()
        self.options['current_url'] = '/track'
        self.options['current_coords'] = current_coords
        self.options['json'] = simplejson.dumps(self.options)
        return self.get_template('track')

    def command(self, current_coords):
        self.options = self.get_options()
        self.options['current_url'] = '/command'
        self.options['current_coords'] = current_coords
        return self.get_template('command')

    def get_template(self, file_name):
        template = self.environment.get_template(file_name + '.html')
        return template.render(options=self.options)


class DroneDelivery(object):
    def __init__(self, drone):
        self.drone = drone
        self.templates = Templates(self.drone.home_coords)

    @cherrypy.expose
    def index(self):
        return self.templates.index()

    @cherrypy.expose
    def command(self):
        return self.templates.command(self.drone.get_location())

    @cherrypy.expose
    @cherrypy.tools.json_out()
    def vehicle(self):
        return dict(position=self.drone.get_location())

    @cherrypy.expose
    def track(self, lat=None, lon=None):
        # Process POST request from Command
        # Sending MAVLink packet with goto instructions
        #self._log("TRACK() Goto: {0}, {1}".format(location, self.altitude))
        if(lat is not None and lon is not None):
            self.drone.goto([lat, lon], True)

        return self.templates.track(self.drone.get_location())


# Connect to the Vehicle
print('Connecting to vehicle on: %s' % connection_string)
vehicle = connect(connection_string, wait_ready=True)

print('Launching Drone...')
Drone().launch()

print('Waiting for cherrypy engine...')
cherrypy.engine.block()

if not args.connect:
    # Shut down simulator if it was started.
    sitl.stop()Message ID: ***@***.***>
