### ISSUE TITLE
Hi, got latest pyG5 working with PX4 pixhawk mavlink and pyEfis

### ISSUE THREAD

**Issue by jerryfat** [blauret/pyG5#15]
Hi:
I was able to modify your latest pyG5 distro code to work with PX4 pixhawk mavlink over radios or ip or sitl, I have attached pic and vid , will get code up on github. I reuse youre repo and code. 
I modified in my repo pyG5Network.py
I can now send messages to pyG5 and pyEfis from mavlink PX4 autopilot or gazebo sitl for virtual testing wo hardware.
not sure u can see these files I attached below: an mp4 and png
Finest Regards, -Jerry Fat 
https://github.com/blauret/pyG5/assets/8506407/099c6912-0b37-410b-9eb5-f095080e8f71

![Screenshot from 2023-11-30 17-57-49](https://github.com/blauret/pyG5/assets/8506407/a5ce0a9d-f825-4bf6-b450-b68b9796542e)

**Comment by blauret** [comment]
If you want to share the code to add that in the release, you are welcome.

**Comment by jerryfat** [comment]
Hi:

I am working on getting data from mavsdk too, and will share all the code etc, 
 instead of using dronekit mauvutil I also made a mavsdk version ,
dronekt and mavutil are broken in python 3.10 if user doesnt patch a python file
I would like your opinions on making my code better,
my code is crude but works for now
I ended up changing out your datahandler with my own simple udp listener and reusing the port number for now
it's not a pretty sight lol
Thanks will contact u soon
-Jerry Fat
Finest Regards and thanks for nice code


     On Monday, December 11, 2023 at 07:05:59 AM EST, blauret ***@***.***> wrote:  
 
 


If you want to share the code to add that in the release, you are welcome.

**Comment by jerryfat** [comment]
Hi Ben:

I just released ver 2 with support for MAVSDK libs which dont break like the Dronekit libs do after python ver 3.10
I updated the readme after release syme typos
https://github.com/jerryfat/FIX-Gateway/blob/master/README-MAVPX4.md

Thanks and Finest Regards,
-Jerry Fat
***@***.***

P.S. Thanks for new release of PyG5 it looks great

from https://github.com/jerryfat/FIX-Gateway/blob/master/README-MAVPX4.md:
## to install everything (PyG5,pyEfis,FIXGW): 
### 
create new dir 
$ mkdir newdir 
$ cd newdir 
clone the modified pyEfis and FIXGW and pyG5 repos: 
$ git clone https://github.com/jerryfat/FIX-Gateway.git 
$ git clone https://github.com/jerryfat/pyEfis.git 
$ git clone https://github.com/blauret/pyG5.git 
install all the dependencies below instructions 
$ pip install mavsdk
# to run apps individually
$cd FIX-Gateway 
note that default.yaml config also starts up FIX server, pyEfis, pyG5 and sitl if ip addr is 172.17.0.1 or :14550 if qgcs or connects to mavlink source over /dev/serial acmo or usb0 
$ python3 ./fixgw.py -v -d -config-file "fixgw/configs/default.yaml" 


     On Monday, December 11, 2023 at 07:05:59 AM EST, blauret ***@***.***> wrote:  
 
 


If you want to share the code to add that in the release, you are welcome.

**Comment by blauret** [comment]
Hi @jerryfat, closing this issue. If there's any code to merge in PyG5 please let me know.

**Comment by jerryfat** [comment]
yes if u want tpo somehow merge my chnages, i used a copy of your network manager code from you that i modified
i will send link in a few hours and explanation
here is my doc so far i still need to finish
https://github.com/jerryfat/FIX-Gateway/blob/master/README-MAVPX4.md
-Jerry Fat

     On Thursday, June 13, 2024 at 03:02:52 AM EDT, Ben Lauret ***@***.***> wrote:  
 
 


Hi @jerryfat, closing this issue. If there's any code to merge in PyG5 please let me know.
