### ISSUE TITLE
sudo pip3 install pyside6 does not work 

### ISSUE THREAD

**Issue by bodote** [blauret/pyG5#18]
Using Raspberry Pi 4, Raspberry Pi Imager and Raspberry Pi OS (32-bit) (based on Debian Bookworm) from 2024-03-15, 
`python3 -m venv myenv && source myenv/bin/activate && pip3 install pyside6`  does not work , nor does:
`apt-cache search PySide6 does not find anything to install `

now I am trying to build QT6 on Raspberry Pi OS  and pyside6 for Python by myself on the Pi4

Any other ideas so far ?

**Comment by blauret** [comment]
It should work on the 64 bit platform. At least that's what I'm using. Maybe you need to install Qt6 first. I'm not sure about that.

**Comment by bodote** [comment]
you are right, works with 64bit, thank you !

**Comment by bodote** [comment]
but it appears, that you actually should not use `sudo pip3 install pyside6` but instead it seems recommended to do a `python3 -m venv myenv && source myenv/bin/activate && pip3 install pyside6` 

then bootstrap.sh worked on raspi but failed on MacOS with : 

```
Successfully installed wheel-0.43.0
ERROR: Ignored the following versions that require a different python version: 6.2.2 Requires-Python >=3.6, <3.11; 6.2.2.1 Requires-Python >=3.6, <3.11; 6.2.3 Requires-Python >=3.6, <3.11; 6.2.4 Requires-Python >=3.6, <3.11; 6.3.0 Requires-Python <3.11,>=3.6; 6.3.1 Requires-Python <3.11,>=3.6; 6.3.2 Requires-Python <3.11,>=3.6; 6.4.0 Requires-Python <3.11,>=3.6; 6.4.0.1 Requires-Python <3.12,>=3.7; 6.4.1 Requires-Python <3.12,>=3.7; 6.4.2 Requires-Python <3.12,>=3.7; 6.4.3 Requires-Python <3.12,>=3.7; 6.5.0 Requires-Python <3.12,>=3.7; 6.5.1 Requires-Python <3.12,>=3.7; 6.5.1.1 Requires-Python <3.12,>=3.7; 6.5.2 Requires-Python <3.12,>=3.7; 6.5.3 Requires-Python <3.12,>=3.7
ERROR: Could not find a version that satisfies the requirement PySide6==6.5.3 (from versions: 6.6.0, 6.6.1, 6.6.2, 6.6.3, 6.6.3.1, 6.7.0, 6.7.1)
ERROR: No matching distribution found for PySide6==6.5.3
```
which could be fixed by changing the requirements.txt. to "6.6.3.1"

Then running `pyG5DualStacked` according to the `Readme.md` does not work : 
raspi: 
```
bodo@raspberrypi:~/dev/pyG5 $ source .venv/bin/activate
(.venv) bodo@raspberrypi:~/dev/pyG5 $ echo $VIRTUAL_ENV
/home/bodo/dev/pyG5/.venv
(.venv) bodo@raspberrypi:~/dev/pyG5 $ python Scripts/pyG5DualStacked
Traceback (most recent call last):
  File "/home/bodo/dev/pyG5/Scripts/pyG5DualStacked", line 6, in <module>
    from pyG5.pyG5Main import pyG5App
ModuleNotFoundError: No module named 'pyG5'
(.venv) bodo@raspberrypi:~/dev/pyG5 $ 
```
MaOS: 

```
(.venv) ~/dev/flightsim_raspi/pyG5 (main) $ python3 Scripts/pyG5DualStacked 
Traceback (most recent call last):
  File "/Users/bodo.teichmann/dev/flightsim_raspi/pyG5/Scripts/pyG5DualStacked", line 6, in <module>
    from pyG5.pyG5Main import pyG5App
ModuleNotFoundError: No module named 'pyG5'
```

**Comment by blauret** [comment]
Readme says:

`python -m pyG5.pyG5Main`

**Comment by blauret** [comment]
Requirements file is updated and works with macOS. I don't have my RPi at hands so I can't verify for now.

**Comment by bodote** [comment]
yeah, `python -m pyG5.pyG5ViewTester` worked indeed on the MacOS, on the raspi , seems needs a fresh install since it does not reboot any longer after I tried that ....

**Comment by blauret** [comment]
Annoying....

**Comment by blauret** [comment]
Is there a reason you are trying to run from the source an not the pipy package?

**Comment by bodote** [comment]
I am not aware that there is an alternativ method to run it. I am Java developer for a living, but quite new to python. Actually I hope to contribute to this project , so running from the source seems ok to me, right ?

**Comment by blauret** [comment]
Go back to the Readme/Installation: https://github.com/blauret/pyG5?tab=readme-ov-file#installation

You can just install the pre-built package and run the "executable". 

if you want to change the code, then you should to run from the virtual environment.

**Comment by bodote** [comment]
thank you! 

I got it to run on my raspberry Pi 4 with a 7inch HDMI Display-C from lafvintech.com. The latter needed a kind of special display driver to make the display rotate. Now it works so far.  

The only thing I needed to add was 
`sudo apt install libxcb-xinerama0 libxcb-cursor0 libxkbcommon-x11-0` for pyside6 to work. 

May this, and the fact that it only works on the 64-bit raspberry pi 4 should be added to the README.md ? 
Would you accept a pull request for this ?

**Comment by blauret** [comment]
> May this, and the fact that it only works on the 64-bit raspberry pi 4 should be added to the README.md ?
> Would you accept a pull request for this ?

Of course. please go ahead

**Comment by blauret** [comment]
Should we close this one?

**Comment by bodote** [comment]
yes
